Update CONTRIBUTING.md
Currently the `sudo` flag on the brew-gem command fails with an unsupported error. This library no longer supports installing the jekyll bundler under root.

Update to remove `sudo`, which works fine for installing the bundler.

```
➜  docs git:(main) sudo brew-gem install jekyll bundler
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```